apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: ml-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        ports:
        - containerPort: 9000
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ml-workflow
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: minio-api
  - port: 9001
    targetPort: 9001
    name: minio-console
  selector:
    app: minio