apiVersion: v1
kind: Namespace
metadata:
  name: ml-workflow
---
apiVersion: batch/v1
kind: Job
metadata:
  name: model-batch-inference
  namespace: ml-workflow
spec:
  template:
    metadata:
      labels:
        app: model-batch-inference
    spec:
      restartPolicy: OnFailure
      containers:
      - name: model-batch-inference
        image: alameda_batch_inference:26.05.1
        imagePullPolicy: Never
        resources:
          requests:
            memory: 3Gi
          limits:
            memory: 4Gi
        env:
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: MLFLOW_TRACKING_URI
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: MINIO_ENDPOINT
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: ml-config
              key: MINIO_SECRET_KEY
        - name: IMG_TAG
          value: "26.05.1"
        - name: PREDICT_PREFIX
          value: "25.05.3"