apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-monitoring
  labels:
    app: model-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-monitoring
  template:
    metadata:
      labels:
        app: model-monitoring
    spec:
      containers:
      - name: model-monitoring
        image: alameda_model_monitoring:25.05.1
        ports:
        - containerPort: 8501
        env:
        - name: DATA_PREFIX
          value: "25.05.3"
        envFrom:
        - configMapRef:
            name: ml-config
        resources:
          requests:
            memory: "4Gi"
          limits:
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: model-monitoring
spec:
  selector:
    app: model-monitoring
  ports:
  - port: 80
    targetPort: 8501
  type: ClusterIP
