apiVersion: v1
kind: Namespace
metadata:
  name: ml-workflow
---
apiVersion: batch/v1
kind: Job
metadata:
  name: model-batch-inference
  namespace: ml-workflow
spec:
  template:
    metadata:
      labels:
        app: model-batch-inference
    spec:
      restartPolicy: OnFailure
      containers:
      - name: model-batch-inference
        image: alameda_batch_inference:25.05.1
        imagePullPolicy: Never
        resources:
          requests:
            memory: 3Gi
          limits:
            memory: 4Gi
        envFrom:
        - configMapRef:
            name: ml-config
        env:
        - name: IMG_TAG
          value: "25.05.1"
        - name: PREDICT_PREFIX
          value: "25.05.1"