apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
  namespace: ml-workflow
  labels: ml-config
data:
  MINIO_ENDPOINT: "minio.ml-workflow.svc.cluster.local:9000"
  FEATURE_STORE_DB: "feature-store-db"
  MLFLOW_TRACKING_URI: "http://mlflow.ml-workflow.svc.cluster.local:5000"